# Generated by Django 4.2.6 on 2023-10-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.IntegerField(default=4000000000),
            preserve_default=False,
        ),
    ]
